[package]
name = "quadtree-demo"
version = "0.1.0"
authors = ["Stan Drozd <drozdziak1@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.4"
log = "0.4"
env_logger = "0.6"
rand = "0.6"
nalgebra = "0.17"
failure = "0.1"
snowflake = "1.3.0"
